"""
State definitions for LangGraph multi-agent orchestration system.

This module defines the state schema used by LangGraph to manage
the flow of information between specialized agents.
"""
from typing import Annotated, List, Dict, Optional, Any
import sys
# Use typing_extensions.TypedDict for Python < 3.12 compatibility
if sys.version_info >= (3, 12):
    from typing import TypedDict
else:
    from typing_extensions import TypedDict
from pydantic import BaseModel, Field
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from src.schemas.vacancy import Vacancy


class UserProfile(BaseModel):
    """
    User profile model containing candidate information.
    
    This model captures all relevant information about a job candidate
    to enable effective matching with job vacancies.
    """
    summary: str = Field(
        "",
        description="Short summary of the candidate profile"
    )
    skills: List[str] = Field(
        default_factory=list,
        description="List of technical and professional skills"
    )
    experience_years: int = Field(
        0,
        ge=0,
        description="Total years of professional experience"
    )
    location_pref: str = Field(
        "",
        description="Preferred job location (e.g., 'San Francisco', 'Remote', 'London')"
    )
    salary_expectation: int = Field(
        0,
        ge=0,
        description="Salary expectation as an integer"
    )
    salary_min: int = Field(
        0,
        ge=0,
        description="Minimum salary filter as an integer"
    )
    company_stage_pref: List[str] = Field(
        default_factory=list,
        description="Preferred company stages (e.g., 'Seed', 'Series A', 'Growth')"
    )
    target_seniority: str = Field(
        "",
        description="Target seniority preference (e.g., 'Junior', 'Mid', 'Senior')"
    )
    industries: List[str] = Field(
        default_factory=list,
        description="Preferred industries (e.g., 'Bio + Health', 'Fintech')"
    )

    class Config:
        """Pydantic configuration."""
        json_schema_extra = {
            "example": {
                "summary": "Backend engineer with platform focus.",
                "skills": ["Python", "FastAPI", "PostgreSQL", "Docker"],
                "experience_years": 5,
                "location_pref": "San Francisco",
                "salary_expectation": 150000,
                "salary_min": 150000,
                "company_stage_pref": ["Series A", "Growth"],
                "target_seniority": "Mid",
                "industries": ["Enterprise", "Fintech"]
            }
        }


class AgentState(TypedDict):
    """
    LangGraph state schema for multi-agent orchestration.
    
    This TypedDict defines the complete state that flows through
    the LangGraph workflow, containing all information needed by
    the various specialized agents.
    """
    messages: Annotated[List[AnyMessage], add_messages]
    """Chat message history. New messages are automatically appended."""
    
    user_profile: UserProfile
    """User profile containing candidate information (skills, experience, preferences)."""

    cv_text: Optional[str]
    """Editable CV content attached by the user."""

    is_cv_attached: bool
    """Whether the user has attached a CV in the UI."""
    
    candidate_pool: List[Vacancy]
    """List of candidate vacancies retrieved from the search."""
    
    match_results: List[Dict]
    """List of match results containing scores and summaries for each vacancy."""
    
    search_params: Dict
    """Search parameters and filters for Pinecone vector search."""
    
    status: str
    """Current stage/status of the workflow (e.g., 'gathering_info', 'searching', 'matching')."""
    
    missing_info: List[str]
    """List of missing information fields that agents should ask the user about."""

    missing_questions: List[str]
    """Human-readable questions generated by the strategist for missing fields."""

    internal_feedback: Optional[Dict[str, Any]]
    """Internal feedback from agents (e.g., JobScout errors or suggestions)."""

    violations: Optional[List[Dict[str, Any]]]
    """Validation violations for strategist explanations."""

    search_failed_reason: Optional[str]
    """Reason for search failures (e.g., filters used with 0 results)."""
