"""
State definitions for LangGraph multi-agent orchestration system.

This module defines the state schema used by LangGraph to manage
the flow of information between specialized agents.
"""
from typing import Annotated, List, Dict, Optional
import sys
# Use typing_extensions.TypedDict for Python < 3.12 compatibility
if sys.version_info >= (3, 12):
    from typing import TypedDict
else:
    from typing_extensions import TypedDict
from pydantic import BaseModel, Field
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from src.schemas.vacancy import Vacancy


class UserProfile(BaseModel):
    """
    User profile model containing candidate information.
    
    This model captures all relevant information about a job candidate
    to enable effective matching with job vacancies.
    """
    skills: List[str] = Field(
        default_factory=list,
        description="List of technical and professional skills"
    )
    years_of_experience: Optional[int] = Field(
        None,
        ge=0,
        description="Total years of professional experience"
    )
    salary_expectation: Optional[str] = Field(
        None,
        description="Optional: do not block search if this is missing. Salary expectation (e.g., '$150k', '$120k-$180k', '150000')"
    )
    location: Optional[str] = Field(
        None,
        description="Preferred job location (e.g., 'San Francisco', 'Remote', 'London')"
    )
    remote_preference: Optional[str] = Field(
        None,
        description="Remote work preference: 'remote_only', 'hybrid', 'onsite', or None"
    )
    visa_status: Optional[str] = Field(
        None,
        description="Visa or work authorization status (e.g., 'US citizen', 'H1B', 'requires_sponsorship')"
    )
    target_role: Optional[str] = Field(
        None,
        description="Target role or job title (e.g., 'Visual Designer', 'Backend Engineer')"
    )
    category: Optional[str] = Field(
        None,
        description="Preferred job category (e.g., 'Design', 'Engineering')"
    )
    experience_level: Optional[str] = Field(
        None,
        description="Preferred experience level (e.g., 'Junior', 'Mid', 'Senior')"
    )
    industry: Optional[str] = Field(
        None,
        description="Preferred industry (e.g., 'Bio + Health', 'Fintech')"
    )
    company_stage: Optional[str] = Field(
        None,
        description="Preferred company stage (e.g., 'Seed', 'Series A', 'Growth')"
    )
    skip_questions: bool = Field(
        False,
        description="Whether the user chose to skip clarifying questions"
    )

    class Config:
        """Pydantic configuration."""
        json_schema_extra = {
            "example": {
                "skills": ["Python", "FastAPI", "PostgreSQL", "Docker"],
                "years_of_experience": 5,
                "salary_expectation": "$150k",
                "location": "San Francisco",
                "remote_preference": "hybrid",
                "visa_status": "US citizen",
                "target_role": "Backend Engineer",
                "category": "Engineering",
                "experience_level": "Mid",
                "industry": "Enterprise",
                "company_stage": "Growth",
                "skip_questions": False
            }
        }


class AgentState(TypedDict):
    """
    LangGraph state schema for multi-agent orchestration.
    
    This TypedDict defines the complete state that flows through
    the LangGraph workflow, containing all information needed by
    the various specialized agents.
    """
    messages: Annotated[List[AnyMessage], add_messages]
    """Chat message history. New messages are automatically appended."""
    
    user_profile: Optional[UserProfile]
    """User profile containing candidate information (skills, experience, preferences)."""
    
    candidate_pool: List[Vacancy]
    """List of candidate vacancies retrieved from the search."""
    
    match_results: List[Dict]
    """List of match results containing scores and summaries for each vacancy."""
    
    search_params: Dict
    """Search parameters and filters for Pinecone vector search."""
    
    status: str
    """Current stage/status of the workflow (e.g., 'gathering_info', 'searching', 'matching')."""
    
    missing_info: List[str]
    """List of missing information fields that agents should ask the user about."""

    missing_questions: List[str]
    """Human-readable questions generated by the strategist for missing fields."""
